spring.application.name=auth-service
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
spring.cloud.config.import-check.enabled=false
server.port=8088

# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://chinmaybm18:<db_password>@cluster0.y3wsr5v.mongodb.net/capstone?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=capstone
